### ISSUE TITLE
infinity edge case for categorizing change significance

### ISSUE THREAD

**Issue by kirbyquerby** [orijtech/test-gobencher#19]
Looking at this markdown set of tables: https://github.com/orijtech/test-gobencher/pull/18/checks
And the corresponding bencher entry: https://dashboard.github.orijtech.com/benchmark/4984fd0856a64c7e87b72c2fd13996f1

It looks like `alloc/op` and `allocs/op` are incorrectly being categorized as either unchanged or negligible.

![image](https://user-images.githubusercontent.com/6455350/134301232-e492ba59-15d0-4f5b-a629-f43d93fd7e5d.png)
In this screenshot, it looks like `delta` is being set to +Infinity, but pct_delta is unset (and therefore 0). In the [go code](https://github.com/orijtech/bencher/blob/a8cff93734b95c220f76f2526ebdf111e7657655/checks/table.go#L59), we are using `pctDelta` to compute the percent change, which is incorrectly considered 0. It looks like the UI avoids this issue by instead [parsing the `delta` string](https://github.com/orijtech/bencher/blob/8a4d43c2d46535ab599e8f8b846ab7754fd7b7da/ui/src/components/Benchmarks/BenchmarkTableList.tsx#L25).

We should adjust the backend to do the same thing, since `pct_delta` doesn't appear to be set when `delta` is infinity (despite floating point numbers being able to represent infinity >:( ).

(it's weird because looking at [the source](https://go.googlesource.com/perf/+/refs/heads/master/benchstat/table.go#107), it seems like `pctDelta` would still be set for infinity. `¯\_(ツ)_/¯`)

**Comment by cuonglm** [comment]
You may want to read this: https://github.com/orijtech/bencher/blob/a8cff93734b95c220f76f2526ebdf111e7657655/pbutil/benchstat.go#L44

Also, do you mean create the issue in orijtech/bencher repo instead?

**Comment by kirbyquerby** [comment]
I certainly did 😅. Thanks Cuong :)
